// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"
)

type Project struct {
	ID          int       `json:"id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	Status      string    `json:"status"`
	WorkspaceID int       `json:"workspaceId"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Goal struct {
	ID          int        `json:"id"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Priority    string     `json:"priority"`
	DueDate     *time.Time `json:"dueDate"`
	Status      string     `json:"status"`
	ProjectID   int        `json:"projectId"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}

type Task struct {
	ID          int        `json:"id"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Status      string     `json:"status"`
	Priority    string     `json:"priority"`
	DueDate     *time.Time `json:"dueDate"`
	GoalID      *int       `json:"goalId"`
	ProjectID   int        `json:"projectId"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}

type Tag struct {
	ID        int        `json:"id"`
	Name      string     `json:"name"`
	Color     string     `json:"color"`
	ParentID  *int       `json:"parentId"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type Note struct {
	ID         int       `json:"id"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	EntityType string    `json:"entityType"`
	EntityID   int       `json:"entityId"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Workspace struct {
	ID          int        `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}

type Dashboard struct {
	TodayTasks     []*Task           `json:"todayTasks"`
	RecentProjects []*Project        `json:"recentProjects"`
	UpcomingGoals  []*Goal           `json:"upcomingGoals"`
	WorkspaceStats *WorkspaceStats   `json:"workspaceStats"`
}

type WorkspaceStats struct {
	TotalProjects   int `json:"totalProjects"`
	TotalGoals      int `json:"totalGoals"`
	TotalTasks      int `json:"totalTasks"`
	CompletedTasks  int `json:"completedTasks"`
	PendingTasks    int `json:"pendingTasks"`
}

type CreateProjectInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Status      string  `json:"status"`
	WorkspaceID int     `json:"workspaceId"`
}

type UpdateProjectInput struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Status      *string `json:"status"`
	WorkspaceID *int    `json:"workspaceId"`
}

type CreateGoalInput struct {
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Priority    string     `json:"priority"`
	DueDate     *time.Time `json:"dueDate"`
	Status      string     `json:"status"`
	ProjectID   int        `json:"projectId"`
}

type UpdateGoalInput struct {
	Title       *string     `json:"title"`
	Description *string     `json:"description"`
	Priority    *string     `json:"priority"`
	DueDate     *time.Time  `json:"dueDate"`
	Status      *string     `json:"status"`
	ProjectID   *int        `json:"projectId"`
}

type CreateTaskInput struct {
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Status      string     `json:"status"`
	Priority    string     `json:"priority"`
	DueDate     *time.Time `json:"dueDate"`
	GoalID      *int       `json:"goalId"`
	ProjectID   int        `json:"projectId"`
}

type UpdateTaskInput struct {
	Title       *string     `json:"title"`
	Description *string     `json:"description"`
	Status      *string     `json:"status"`
	Priority    *string     `json:"priority"`
	DueDate     *time.Time  `json:"dueDate"`
	GoalID      *int        `json:"goalId"`
	ProjectID   *int        `json:"projectId"`
}

type CreateTagInput struct {
	Name     string `json:"name"`
	Color    string `json:"color"`
	ParentID *int   `json:"parentId"`
}

type UpdateTagInput struct {
	Name     *string `json:"name"`
	Color    *string `json:"color"`
	ParentID *int    `json:"parentId"`
}

type CreateNoteInput struct {
	Title      string `json:"title"`
	Content    string `json:"content"`
	EntityType string `json:"entityType"`
	EntityID   int    `json:"entityId"`
}

type UpdateNoteInput struct {
	Title   *string `json:"title"`
	Content *string `json:"content"`
}

type CreateWorkspaceInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type UpdateWorkspaceInput struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

